# **Numpy Arrays**
Recall Python does not have arrays. <br>
Yet, arrays are really convenient and powerful. <br>
To use arrays in Python, import Numpy.<br>

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. <br><br>
The elements of a NumPy array, or simply an array, are usually numbers, but can also be boolians, strings, or other objects. *When the elements are numbers, they must all be of the same type. For example, they might be all integers or all floating point numbers.*<br><br>
The NumPy arrays takes significantly less amount of memory as compared to python lists.

# **Import Numpy**

In [7]:
import numpy as np

# **Create an Array**

In [ ]:
#Create an array of 2 row and 3 columns
a = np.array([[1, 2, 3],[2,4,6]])   
print(type(a))           
print(a.shape)            


**Print an array**

In [ ]:
print(a)  

**Change a value in an array**<br>
There are two ways to access a value in a Numpy array<br>
>array_name[row number, column number]<br>
>array_name[row number][colu,mn number]

In [ ]:
#Change the value at location (0,0)
a[0][0] = 5                  
print(a)     
print("")
#Change the value at location (1,1)
a[1,1] = 44
print(a)


1. Create a 4x4 Numpy array<br>
2. Print the values at (0,0)(1,1)(2,2)(3,3)


In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16]])

print(a[0,0], a[1][1],a[2,2], a[3][3])

1 6 11 16


# **Create Filled Arrays**
Numpy allows you to create arrays filled with zeros, ones, a specific number, an identity matrix, and an array filled with random numbers.

**An array of all zeros**<br>
np.zeros((number of rows, number of columns))

In [ ]:
a = np.zeros((7,9))   
print(a)              

**An array of all ones**<br>
np.ones((number of rows, number of columns))

In [ ]:
b = np.ones((5,4))    
print(b)              


Arrays of: <br>
>A specific number<br>
>>np.full((no. of rows, no of col), number for filling)<br>
<br>

>An identity matrix<br>
>>np.eye(matrix dimension)<br>
<br>

>An index filled with random numbers
>>np.random.random((no. of rows, no of col))


Create and print the following arrays<br>
1. A 12x10 array filled with the number 45.333<br>
2. A 25x25 identity matrix<br>
3. A 12x30 array filled with random numbers

In [ ]:
print(np.full((12,10), 45.33))

print(np.eye(25))

print(np.random.random((12,30)))

# **Slice an Array**
Numpy arrays can be sliced into smaller arrays of different sizes. 

In [ ]:
#Slicing an array

#Create an array of the following size and values
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)


**Slice the array**<br>
Slice an array using: 
new_array = original_array[first row:last row, first col, last col]

In [ ]:
#Create a new array from the center four values
#[[6   7]
# [10 11]]

b = a[1:3, 1:3]
print(b)

**Sliced arrays are changed when the new array or the original array are changed**

In [ ]:
print(a)
print("")

#Change a value in the new array
b[0,0] = -22

#Notice -- the value in b was changed. 
#And the value in a was also changed
print(a)

In [ ]:
print(b)
print("")

#Change a value in the new array
a[1,1] = -8888

#Notice -- the value in a was changed. 
#And the value in b was also changed
print(b)

1. Create the following array: 
>[2,6,9,12]<br>
>[5,1,1,8]<br>
>[7,7,5,9]<br>
>[8,9,5,2]<br>

2.Slice the array into two (non-overlapping) 4x2 arrays<br>
3.Change 5 values in the original array. <br>
4.Print the two new arrays, check that the values have changed. <br>


In [12]:


a = np.array([[2,6,9,12], [5,1,1,8], [7,7,5,9], [8,9,5,2]])
print(a)
b = a[0:2, 0:2]
print(b)
c = a[2:4,2 :4]
print(c)

a[1,0] = 60
print(a)
print(b)
print(c)

[[ 2  6  9 12]
 [ 5  1  1  8]
 [ 7  7  5  9]
 [ 8  9  5  2]]
[[2 6]
 [5 1]]
[[5 9]
 [5 2]]
[[ 2  6  9 12]
 [60  1  1  8]
 [ 7  7  5  9]
 [ 8  9  5  2]]
[[ 2  6]
 [60  1]]
[[5 9]
 [5 2]]


# **Reshaping Arrays**

Numpy has a built in function that allows the user to reshape arrays. <br>
>array-name.reshape(number of rows, number of col)<br>
<br>
The new shape has to have the same number of elements as the old shape. 
<br>
For example:<br>
If the array has a shape of 3x4 (12 elements) it can be reshaped to:<br>
>12x1<br>
>1x12<br>
>2x6<br>
>6x2<br>
>4x3<br>

In [ ]:
#Reshape an array
#Step 1: create an array
#Use arange to create an array of evenly
#spaced integers from 0 - 23
a = np.arange(24)
print(a)
#The shape of this array is a vector
print(a.shape)
#Step 2: change the shape of array a
a.reshape(8,3)


1. Create an array that has 32 elements. 
2. Reshape it into: 
> an array 8x4<br>
>an array 2x16<br>


In [13]:

a = np.arange(32)
print(a)
print(a.shape)
print(a.reshape(8,4))
print(a.reshape(2,16))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
(32,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


**Reshape an array into three or more dimensions**
Numpy arrays can also be reshaped into multiple dimensions. 
Use the form:<br>
>array-name.reshape(dimension 1, no. of rows, no. of cols)<br>

The criteria about the number of elements must still be obeyed. 



1. Create an array of 72 elements
2. Reshape the array into 12x3x2 

In [14]:

a = np.arange(72)
print(a.reshape(12, 3, 2))


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]]

 [[36 37]
  [38 39]
  [40 41]]

 [[42 43]
  [44 45]
  [46 47]]

 [[48 49]
  [50 51]
  [52 53]]

 [[54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]]

 [[66 67]
  [68 69]
  [70 71]]]


# **Creating an Array from Data in a File**
Numpy allows the user to create arrays from the contents of a file. 


Step 1: Check the access and pathname for the file to be read

# **Import genfromtxt**
Use genfromtxt to generate the array from the text file. 
<br>
When reading in data from files, you need to specify the data type. Usually Numpy arrays are used for numbers. <br>
<br>
For the chord-progressions.csv file, there is integer data and string data. <br>
To read it into a Numpy array, you must specify the datatype for each column. <br>
i1 = integer<br>
S20 = string<br>
skip_header will ignore the header row <br> 

In [2]:
from numpy import genfromtxt
chords = genfromtxt("chordProgression.csv",  
                    delimiter=',',skip_header=1, dtype=[('1st chord','i1'),('2nd chord','i1') , ('3rd chord','i1'),
                                          ('4th chord','i1'), ('Progression Quality', 'S20')])

In [3]:
print(chords)

[(6, 4, 1, 5, b'Alternative') (4, 4, 1, 5, b'Catchy')
 (1, 1, 1, 1, b'Didgeridoo') (1, 6, 4, 5, b'Dreadful')
 (1, 6, 2, 5, b'Dreadful') (1, 6, 2, 4, b'Endless')
 (1, 3, 4, 6, b'Energetic') (1, 5, 1, 4, b'Folk') (1, 6, 1, 4, b'Folk')
 (6, 5, 4, 3, b'Flamenco') (6, 5, 6, 5, b'Flamenco')
 (1, 4, 3, 6, b'Grunge') (2, 5, 1, 6, b'Jazz') (1, 4, 5, 4, b'Love')
 (1, 4, 1, 5, b'Memories') (1, 5, 6, 4, b'Pop') (1, 6, 3, 7, b'Pop')
 (4, 1, 4, 5, b'Rebellious') (1, 4, 5, 5, b'Sad') (1, 5, 4, 4, b'Sad')
 (1, 4, 5, 4, b'Sad') (5, 4, 1, 1, b'Sweet') (1, 4, 1, 4, b'Simple')
 (1, 5, 5, 1, b'Simple') (1, 4, 1, 4, b'Wildside')
 (1, 1, 4, 6, b'Wistful') (2, 1, 5, 7, b'Moody') (2, 1, 7, 6, b'Moody')]


In [4]:
print(chords.shape)
cReshape = chords.reshape(28,1)
print(cReshape)

(28,)
[[(6, 4, 1, 5, b'Alternative')]
 [(4, 4, 1, 5, b'Catchy')]
 [(1, 1, 1, 1, b'Didgeridoo')]
 [(1, 6, 4, 5, b'Dreadful')]
 [(1, 6, 2, 5, b'Dreadful')]
 [(1, 6, 2, 4, b'Endless')]
 [(1, 3, 4, 6, b'Energetic')]
 [(1, 5, 1, 4, b'Folk')]
 [(1, 6, 1, 4, b'Folk')]
 [(6, 5, 4, 3, b'Flamenco')]
 [(6, 5, 6, 5, b'Flamenco')]
 [(1, 4, 3, 6, b'Grunge')]
 [(2, 5, 1, 6, b'Jazz')]
 [(1, 4, 5, 4, b'Love')]
 [(1, 4, 1, 5, b'Memories')]
 [(1, 5, 6, 4, b'Pop')]
 [(1, 6, 3, 7, b'Pop')]
 [(4, 1, 4, 5, b'Rebellious')]
 [(1, 4, 5, 5, b'Sad')]
 [(1, 5, 4, 4, b'Sad')]
 [(1, 4, 5, 4, b'Sad')]
 [(5, 4, 1, 1, b'Sweet')]
 [(1, 4, 1, 4, b'Simple')]
 [(1, 5, 5, 1, b'Simple')]
 [(1, 4, 1, 4, b'Wildside')]
 [(1, 1, 4, 6, b'Wistful')]
 [(2, 1, 5, 7, b'Moody')]
 [(2, 1, 7, 6, b'Moody')]]



1. Read the file /content/cloned-repo/airtravel.csv
2. Ignore the header row
3. Create a Numpy array with the data
4. Convert the months to numbers (JAN = 1,FEB=2, ...Dec=12)

Hint:<br><br>
Make sure you understand what value is stored in the array|<br>
print("airtravel[0][0] = ",airtravel[0][0])


[numpy.genfromtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html)


In [5]:

travels = genfromtxt("airtravel.csv",  
                    delimiter=',',skip_header=1, dtype=[('Month','S20'),('1958','i4') , ('1959','i4'), ('1960','i4')])
print(travels)
rstravels = travels.reshape(1,12)
print(rstravels)
print(rstravels[0][0][0])
for i in range(rstravels.size):
  rstravels[0][i][0] = i+1
print(rstravels)

[(b'JAN', 340, 360, 417) (b'FEB', 318, 342, 391) (b'MAR', 362, 406, 419)
 (b'APR', 348, 396, 461) (b'MAY', 363, 420, 472) (b'JUN', 435, 472, 535)
 (b'JUL', 491, 548, 622) (b'AUG', 505, 559, 606) (b'SEP', 404, 463, 508)
 (b'OCT', 359, 407, 461) (b'NOV', 310, 362, 390) (b'DEC', 337, 405, 432)]
[[(b'JAN', 340, 360, 417) (b'FEB', 318, 342, 391) (b'MAR', 362, 406, 419)
  (b'APR', 348, 396, 461) (b'MAY', 363, 420, 472) (b'JUN', 435, 472, 535)
  (b'JUL', 491, 548, 622) (b'AUG', 505, 559, 606) (b'SEP', 404, 463, 508)
  (b'OCT', 359, 407, 461) (b'NOV', 310, 362, 390) (b'DEC', 337, 405, 432)]]
b'JAN'
[[(b'1', 340, 360, 417) (b'2', 318, 342, 391) (b'3', 362, 406, 419)
  (b'4', 348, 396, 461) (b'5', 363, 420, 472) (b'6', 435, 472, 535)
  (b'7', 491, 548, 622) (b'8', 505, 559, 606) (b'9', 404, 463, 508)
  (b'10', 359, 407, 461) (b'11', 310, 362, 390) (b'12', 337, 405, 432)]]


# **Airthmetic Operations**
Numpy can perform arithmetic operations on arrays very easily. 
The form for artihmetic operations is: <br>
>np.operation(array1, array2)<br>

The available operations are: <br>
>add<br>
>subtract<br>
>multiply<br>
>divide<br>


In [8]:
#Arithmetic Operations
array1 = np.arange(9).reshape(3,3)
print("Array1 = \n", array1)

array2 = np.arange(4,13).reshape(3,3)
print("Array2 = \n", array2)

Array1 = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array2 = 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
sum = np.add(array1, array2)
print(sum)

[[ 4  6  8]
 [10 12 14]
 [16 18 20]]



1. Create two 5x5 arrays
2. Multiply them, 
3. Subract one from the other
4. Divide one into the other. 


In [ ]:

a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))


**Dot Product**<br>
>a · b = ax × bx + ay × by<br>

For more than two dimensions....<br>
>a · b = ax × bx + ay × by + az × bz<br>

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])
print(v)
print(w)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

If you are interested in learning more about linear algebra functions, check out this link<br>
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


Find the dot product of:<br>
[22,33,44] [11,22,33]

In [ ]:
v = np.array([22,33,44])
w = np.array([11,22,33])
print(v.dot(w))
print(np.dot(v,w))

# **Sorting Arrays**

Numpy has a built-in sort function. <br>
It has the form: 
>np.sort(array name)


In [ ]:
#Sorting arrays
array1 = np.array([[6,3,1,2], [9,11,6,5], [6,4,7,0]])
print(array1)

In [ ]:
#Sort the columns
array_sorted = np.sort(array1, axis=0)
print(array_sorted)

In [ ]:
#Sort the rows
array_sorted = np.sort(array1, axis=1)
print(array_sorted)


1. Create an array with the following values: <br>
>[4,8,1,0,99]
>[1,22,0,76,43]
>[7,7,90,54,3]

2. Sort it along the x axis
3. Sort it along the y axis


In [10]:

a = np.array([[4,8,1,0,99], [1,22,0,76,43], [7,7,90,54,3]])
print(a)
#x-axis
print(np.sort(a, axis=1))
#y-axis
print(np.sort(a, axis=0))

[[ 4  8  1  0 99]
 [ 1 22  0 76 43]
 [ 7  7 90 54  3]]
[[ 0  1  4  8 99]
 [ 0  1 22 43 76]
 [ 3  7  7 54 90]]
[[ 1  7  0  0  3]
 [ 4  8  1 54 43]
 [ 7 22 90 76 99]]


**Text in Numy Arrays**
Numpy arrays can also sort text 


In [ ]:
array1 = np.array([['w','c'], ['z','f']])
print(array1)
print(np.sort(array1,axis=1))


1. Create an array with the following values: 
>['dog','fish','cat']<br>
['zebra', 'mouse', 'ox']<br>

2. Sort on the x-axis 
3. Sort on the y-axis


In [ ]:
a = np.array([['dog','fish','cat'],['zebra', 'mouse', 'ox']])
print(a)
print(np.sort(a, axis=1))
print(np.sort(a, axis=0))

**Sort an array based on a parameter**<br>
A Numpy array can be created with parameter names and types identified. <br>
Then the array can be sorted based on the parameter name. <br>
<br>
Step 1: Create an array with parameter names and types 
Step 2: Sort the array with the form:<br>
>np.sort(array name, order = 'parameter name')


In [ ]:
#Sorting arrays by parameter name
#Step 1: create the array with parameter names and types
dt = np.dtype([('name', 'S10'), ('zipcode', int)])
array1 = np.array([('Joe', 95120), ('Mark', 95122), ('Sue', 90210)], dtype=dt)
print(array1)

#The b in the output is for bytestrings

In [ ]:
#Step 2: Sort the array by zipcode
print(np.sort(array1, order='zipcode'))
print(np.sort(array1, order='name'))


1. Create an array of 10 students with the following information
>Student name, student ID, student major, student GPA<br>
For example: <br>
> >'Bill', 453221, 'CompSci', 2.3

2. Sort the array by each of the features (name, ID, major, GPA)


In [ ]:
dt = np.dtype([('Name', 'S20'),('ID', int),('Major', 'S20'), ('GPA', float)])
a1 = np.array([('AAA',9001, 'Computers', 50),('cc',9010, 'Maths', 20),('BB',9003, 'Science', 90),('DDD',9002, 'English', 30)], dtype=dt)
print(a1)
print(np.sort(a1, order="Name"))
print(np.sort(a1, order="ID"))
print(np.sort(a1, order="Major"))
print(np.sort(a1, order="GPA"))